# Generated by Django 4.2.25 on 2025-11-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliar_IMC',
            fields=[
                ('CPF', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('Nome', models.CharField(max_length=150)),
            ],
        ),
    ]
