# Generated by Django 4.2.26 on 2025-11-21 14:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliarIMC',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('escola', models.CharField(max_length=150)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('foto', models.ImageField(upload_to='imc_fotos/')),
                ('valor_imc', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
            ],
            options={
                'verbose_name': 'Avaliação de IMC',
                'verbose_name_plural': 'Avaliações de IMC',
                'ordering': ['nome'],
            },
        ),
        migrations.DeleteModel(
            name='Avaliar_IMC',
        ),
    ]
