# Generated by Django 4.2.26 on 2025-11-28 17:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0002_avaliarimc_delete_avaliar_imc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliarimc',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
    ]
