# Generated by Django 4.2.26 on 2025-12-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0003_alter_avaliarimc_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliarimc',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
    ]
